name: Release

on:
  push:
    branches:
      - "master"

permissions:
  contents: read

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 15
    environment: crates_io_release

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2

      - name: "Install Python Libraries"
        run: python -m pip install --user -r requirements.txt
        working-directory: "scripts"

      - name: "Run release script"
        run: "python3 scripts/ci-release.py"
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
